exports.getCategoryId = async (category) => {
    const data = {
        "Film & Animation": 1,
        "Autos & Vehicles": 2,
        "Music": 3,
        "Pets & Animals": 15,
        "Sports": 17,
        "Travel & Events": 19,
        "Gaming": 20,
        "Videoblogging": 21,
        "People & Blogs": 22,
        "Comedy": 23,
        "Entertainment": 24,
        "News & Politics": 25,
        "Howto & Style": 26,
        "Education": 27,
        "Science & Technology": 28,
        "Nonprofits & Activism": 29,
        "Movies": 30,
        "Anime/Animation": 31,
        "Action/Adventure": 32,
        "Classics": 33,
        "Comedy": 34,
        "Documentary": 35,
        "Drama": 36,
        "Family": 37,
        "Foreign": 38,
        "Horror": 39,
        "Independent": 40,
        "Kids": 41,
        "Music": 42,
        "Musical": 43,
        "Mystery": 44,
        "Romance": 45,
        "Sci-Fi/Fantasy": 46,
        "Short Films": 47,
        "Special Interest": 48,
        "Thriller": 49,
        "Western": 50,
        "360 Videos": 90,
        "3D Videos": 91,
        "180 Videos": 92,
        "Virtual Reality": 93,
        "360 Spatial Audio": 101
    }
    return data[category]
}